global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'push'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['push:8000']
  - job_name: 'jaeger'
    metrics_path: /metrics
    static_configs:
      - targets: ['jaeger:14269']
